### PR TITLE
Workarround for method getImageSize. Prevent returning (-1, -1)

### PR DESCRIPTION
**Pull request by andreesg**
Proposed workarround to prevent getImageSize() method from returning (-1, -1) in certain image files.
Uses PIL to get the correct size of the image.

### CODE REVIEW

**Comment by jensens** [comment]
Thanks for the PR, can you add a entry in ``docs/HISTORY.txt``?
Can you provide an image file which result in a (-1, -1) size?
A test with a real file which results in the problem would be superior.
Is the issue valid for master branch too?

**Comment by andreesg** [comment]
@jensens thanks for your reply. 

The docs/HISTORY.txt is updated
Here it goes a link for two image which results in the problem:
http://bit.ly/1Bz6mZz
http://bit.ly/1F2iXae

The workarround will work as well with the master branch

**Comment by djowett** [comment]
Just to point out - this should work without PIL....

    $ bin/zopepy

    >>> import os
    >>> 
    >>> from plone.namedfile import file
    >>> from plone.namedfile.tests.base import getFile
    >>> f = getFile(os.getcwd() + os.sep + '1F2iXae.jpeg')
    >>> data = str(f.read())
    >>> data[0:20]
    '\xff\xd8\xff\xe1"\rExif\x00\x00II*\x00\x08\x00\x00\x00'
    >>> file.getImageInfo(data)
    ('image/jpeg', 3000, 2265)
    >>>

**Comment by jensens** [comment]
It would be really good to have a test with the steps:
- create a problematic namedfile
- show that it has (self._width, self._height) == (-1, -1)
- call getImageSize and show that it has the correct dimensions.

Otherwise we cant be sure to not run into the problem again in future, i.e. after some refactoring or similar.

**Comment by djowett** [comment]
+1 (though the problematic files given are quite big)

**Comment by jensens** [comment]
so the question is: a big file in tests or not testing the problem at all. any opinions @tisto @gforcada @bloodbare ?

**Comment by gforcada** [comment]
@djowett by quite big you mean in the order of few Mb or Gb? If we are talking about Mb, it's not so nice to store them on git, but it will be just one file anyway...

If we talk about +10Mb, then this is indeed not so nice at all... any option to generate the image on the fly?

@jensens for me the question is more: how can we handle that image size, to test or not is out of question (i.e. there must be a test :)

**Comment by djowett** [comment]
@jensens @gforcada 
The files @andreesg was having problems with (above) are 2Mb each, so should be no problem.
My only point was that I'm not sure this needs PIL - as the code I demoed above works on the given files without it.

**Comment by jensens** [comment]
moved to plone, rebased over there, see #17

**Comment by jensens** [comment]
rebased and relocated to plone as branch of this repository

**Pull request closed without merging**
