### PR TITLE
Call new pre_scale and get_or_generate from plone.scale.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
See branch `pre-scale` of plone.scale, in https://github.com/plone/plone.scale/pull/57.

### CODE REVIEW

**Review by MrTango — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Ready for review, but I need to fix tests in `plone.formwidget.namedfile` and `plone.restapi`.

**Comment by MrTango** [comment]
@mauritsvanrees i added a fix here and in plone.scale to prevent some errors the modified parameter was producing in some methods

**Comment by mauritsvanrees** [comment]
I fixed some more and I think this is ready. Some robot failures, but they are unstable currently.

**Comment by mauritsvanrees** [comment]
This could use at least one other reviewer, together with https://github.com/plone/plone.scale/pull/57.
@plone/framework-team @pnicolli @cekk 
Robot tests are failing because they are [unstable](https://github.com/plone/Products.CMFPlone/issues/3542) in general currently.

**Comment by MrTango** [comment]
Added some fixes and examples, it should work now here and in outputfilters

**Comment by MrTango** [comment]
I added title and alt attributes to the picture method, as well as examples for it and added a changelog entry

**Comment by mauritsvanrees** [comment]
I have merged the `pre-scale-picture-tag` branch in here.

**Comment by mauritsvanrees** [comment]
All green in combination with https://github.com/plone/plone.scale/pull/57.
Since no one has objected, I say we merge this tomorrow (Thursday).  Then the work on picture variants and on image scale info in the catalog can continue with less branches of packages.

**Comment by ale-rt** [comment]
I still had no chance to look at this but I fully trust you both :)

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
