### PR TITLE
add pdata support

### PR DESCRIPTION
**Pull request by vangheem**
This is a PR for master.

### CODE REVIEW

**Comment by jensens** [comment]
@vangheem in which case is Pdata passed in a NamedBlobFile? Is it storing an OSF File/Image?

**Comment by davisagli** [comment]
Yeah, I guess that would happen if you take an OFS File/Image and pass its data attribute to a NamedBlobFile.

This looks good to me, but it should be called PdataStorable (not PDataStoragable) for consistency with the other classes in this module and with the capitalization of Pdata in OFS.Image. It'd also be nice to have a test.

**Comment by vangheem** [comment]
Yah, I'll write a test. I was going to write one and then realized none of the others had tests so I got lazy...

**Comment by vangheem** [comment]
updated

**Comment by vangheem** [comment]
updated assertEquals

**Comment by jensens** [comment]
@vangheem one test fails, typo, circular import or whats wrong?

**Comment by vangheem** [comment]
Updated, let's see if tests work this time.

**Pull request merged**
