### PR TITLE
Fixes for scaling/streaming bug that affects Windows 10

### PR DESCRIPTION
**Pull request by smcmahon**
With this fix, all the tests for plone.namedfile pass on Windows 10. Without it, all the scaling tests fail.

Fixes https://github.com/plone/Products.CMFPlone/issues/1627

### CODE REVIEW

**Comment by jensens** [comment]
@smcmahon the tests are failing for some reason.

**Comment by smcmahon** [comment]
Looks like three robot tests failed. I can't see any relationship between these and what I touched (which changed the streaming of data from uncommitted blobs, which only really affected image scaling). plone.namedfile has no robot tests of its own.

**Comment by jensens** [comment]
started tests again. Not all of our robot tests are stable.

**Comment by smcmahon** [comment]
Do we want this change for the 3.0.x branch? If so, I can create a pull request for that also. If we're to have any more in the 5.0.x series, it would be nice to get this included.

**Comment by gforcada** [comment]
@smcmahon I guess it never hurts to backport fixes, right?

**Pull request merged**
