### PR TITLE
2.0.x exif image rotation

### PR DESCRIPTION
**Pull request by ezvirtual**
I reverted changes I had made directly and instead made this, an equivalent pull request of #13 for the 2.0.x / Plone 4.3 branch.

### CODE REVIEW

**Comment by vangheem** [comment]
Thanks for this! Take a look at the inline comments on the other PR.

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-4.3/97/

**Comment by jensens** [comment]
strategy: wait for #13 to be finished and merged, then apply same changes here, test, merge

**Comment by jensens** [comment]
close like #13, read over there for details

**Pull request closed without merging**
