### PR TITLE
Allow access to namedfile attributes from restricted Python

### PR DESCRIPTION
**Pull request by datakurre**
Any reason why attributes should not be accessible? Attributes and methods starting with _ remain protected.

This would allow e.g. to write "maximum file size validator" using collective.ambidexterity.

### CODE REVIEW

**Comment by jensens** [comment]
Shouldn't ``data`` property setter be protected explicitly by ``Modify portal content``?

**Comment by datakurre** [comment]
I thought __allow_access_to_unprotected_subobjects__ only allows getattr. Setter methods start with underscore so they are not callable directly from RestrictedPython. But probably this needs real tests to check all those scenarios, but how? Making at least AccessControl a test dependency?

**Comment by jensens** [comment]
I am also not sure if a ``obj.data = 'somevalue'`` is allowed after allowing access, I guess yes.

``_allow_access_to_unprotected_subobjects__`` can also be a ``dict`` with key as the attribute name and value ``1`` or ``True`` to allow for a defined set of attributes.

**Comment by thet** [comment]
I guess there is no good reason to not allow access to these properties. Probably it's just that no one thought of the use case to allow access to the attributes via restricted Python.

But wouldn't it be nicer to explicitly allow the access to these properties via ``AccessControl.SecurityInfo.ClassSecurityInfo`` decorators?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
