### PR TITLE
Handle missing subpath for @@images view

### LINKED ISSUE #144: Loading /@@images without any subpath raises an error
`ViewNotCallableError: __call__`

Expected: a 400 or 404 response.

### PR DESCRIPTION
**Pull request by davisagli**
Fixes #144

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks!

Two of the three Jenkins jobs have a failure in a robot test.  Should be unrelated, but it is the same test in both cases (Scenario Reorder Folder Contents, which goes wrong more often), so I will run them both again to be sure.

**Comment by mauritsvanrees** [comment]
One of the two jobs got fixed, the other one got a different error.  It may not help that Jenkins is busy with a lot of jobs today.  I will merge.

**Pull request merged**
