### PR TITLE
Drop support for Python 2.7.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Main target is now Plone 6, but we try to keep it running on Plone 5.2 with Python 3.
See discussion at https://github.com/plone/plone.scale/issues/44

Added tox and GitHub Actions so we can check that the package works on various Plone versions, without relying on Jenkins.

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Ready for review.
I have changed coredev 5.2 to use new branch 5.x for plone.namedfile. Master will be for Python 3 only.
Mr Roboto should be smart enough to see that the Plone 5 jobs need not be started now, although they might still be in the list of checks for now.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jensens Could you have a look at this PR please? I have added tox and am using `mxdev` in it for the first time. I realised I needed it because `plone.namedfile` needs to be developed and it is also in the constraints. The `ignores` option helps here.

BTW, my `.tox` directory is about 2.4 GB after a full run. Each environment gets about 350 MB, which is mostly in for example `.tox/plone60-py39/lib/python3.9/site-packages`. Buildout with its shared eggs directory is much more disk efficient. :-)

**Comment by jensens** [comment]
Shared eggs are indeed better disk-wise. I may try to configure my workspaces folder as deduplicated, if this sums up too much (I use ZFS here). 

Btw., I like the tox approach, its very lean and simple.

**Pull request merged**
