### PR TITLE
Support for allowed content types.

### PR DESCRIPTION
**Pull request by thet**
Support to constrain files to specific content types with a "allowedContentTypes" attribute on file and image fields.

Fixes: #157

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]
LGTM

**Comment by thet** [comment]
@petschki tnx for the feedback!
I will quickly simplify some parts for some feedback I got from @ale-rt and will re-submit again.

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks.

**Review by davisagli — COMMENTED** [review]
@thet Nice one!

**Pull request merged**
