### PR TITLE
Range Support

### PR DESCRIPTION
**Pull request by mamico**
Implementation proposal of Range support. eg. useful for serving large video files.

References:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
* https://github.com/plone/plone.app.blob/blob/da465f1089d3e7d8e0ba5189a0d47ff0784024ce/src/plone/app/blob/download.py
* https://github.com/zopefoundation/Zope/blob/b9a346903fe4a6874face0930876184ac321853e/src/ZPublisher/HTTPRangeSupport.py
* https://github.com/zopefoundation/Zope/blob/ab77e9e094d915edad633e49105e62dd6723eee4/src/OFS/Image.py#L183

### CODE REVIEW

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
> This makes `plone.app.caching` a hard dependency. I don't like that, because it is not a dependency of `Products.CMFPlone`, but only of `Plone`. Can you make this a soft dependency?
> From the top of my head, something like this could work:
> ...

Agree with you. Your change proposal is an option, the other could be to move If-Range (not Range, that remains here) logic on p.a.caching. Probably I prefer this approach. What do you think about it?

Formerly (p.a.blob, ..) If-Range/Etag/Last-Modified was all managed in Range implementation, but IMO are all related to caching logic, so better in p.a.caching.

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@mamico I love this fix! I was stumbling over missing range support myself recently. iOS devices cannot play streamed videos served from Plone because of that (having Varnish in front of Zope gives support for range requests for cached files tough).
Where did the if-range support got? There is not a PR in plone.app.caching.

I also wonder if this support shouldn't be implemented more low-level on ZServer.That's where I'd expect range request support.

**Comment by mamico** [comment]
Hi @thet there is not yet a PR in p.a.caching but there is a branch https://github.com/plone/plone.app.caching/tree/if-range-support 
Currently I've no time to work on it, but would be awesome if you could  review/complete the work.
I don't know about the possibility to move this code on Zope level, because part of them is related to caching headers. But if you have  a good idea about to do that, I definitively agree.

**Comment by fredvd** [comment]
I got bitten by the missing ranges support as well last week when I tried to use the file content type to download a movie in Webkit/Safari/IOS. First thought it has something to do with the media format. 

I also tested wildcard.media and found they have added streams support using a widget. I don't exactly understand what happens there, the magic is in https://github.com/collective/wildcard.media/blob/master/wildcard/media/browser/widget.py  , but it seems that is much less code than wat this pull request needs to do. 

 is The wildcard.media add'on re-using other already existing functionality in the blobs packages? One of the comments in the widget.py seem to indicate so:

> Leverages the existing BlobWrapper functionality to stream the media blobs
> to the client, allowing ranges and partial content.

**Comment by pbauer** [comment]
Great!
This fixes https://github.com/plone/Products.CMFPlone/issues/2847

**Comment by fredvd** [comment]
And there are other bug reports/initiatives as well:

https://github.com/plone/Products.CMFPlone/issues/2847

@pbauer In the comments of https://github.com/collective/wildcard.media/pull/57  you mention that the partial streaming support is still broken, was that still the case when you merged the pull request?

**Comment by pbauer** [comment]
Yes, it was.

**Comment by pbauer** [comment]
@mamico I tried making sense of how I would use that in wildcard.media. Can you give me a hint how that could work? Here ist the relevant piece of code where I had to remove the old partial streaming method: https://github.com/collective/wildcard.media/pull/57/files#diff-b66c279de8c3c0c6ef1b092cd722cc6eL30

**Comment by mamico** [comment]
@pbauer  sorry for late respond (I was really busy latest weeks). I saw that wildcard.media use p.f.namedfile, previously I had missed the feature there. So I did https://github.com/plone/plone.formwidget.namedfile/pull/44. Could be easy to do something similar for wildcard.media.

**Comment by mamico** [comment]
Broken tests against plone.restapi seems to me not related to this PR. Same tests are broken also with current plone.namedfile master.

**Pull request merged**
