### PR TITLE
Implemention of PLIP 1673: Automatic image rotation based on Exif data

### PR DESCRIPTION
**Pull request by loechel**
PLIP 1673: https://github.com/plone/Products.CMFPlone/issues/1673
This PLIP implementation introduced a straight foreward image rotation based on Exif information for JPEG and TIFF Images stored in plone.namedfile Image fields.
The concept of Exif orientation is described in detail in the following blog: http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

It requires an additional external library as dependency: piexif (package: https://pypi.python.org/pypi/piexif; docs: http://piexif.readthedocs.org/en/latest/; github: https://github.com/hMatoba/Piexif)
piexif, allows reading and writing of Exif information, which offers more powerful image handling than a read only library. piexif also works very smart together with Pillow.

This PLIP superseeds prior attemts to add Exif based image rotation to plone.namedfile: #12, #13, #14

For testing of orientation change, images where needed to include for test files.
This is not part of this implementation.
The following github repositories have several examples of Images for orientation testing:
- https://github.com/recurser/exif-orientation-examples (JPEG Images with orientation 1-8 in Landscape and Portrait orientation)
- https://github.com/ianare/exif-samples (lots of different JPEG and TIFF Images, even corrupted images)

Additional to the PLIP implementation this commit includes a restructuring of the package.
- Image meta data detection has been moved to a subfolder utils and splited into several files for each image type
- Moved functions to utils as those are helper methods, so that base functionallity is easier to read
- Added basic TIFF Image handling. Prior TIFF were handled as Files not Images.

Last but not least:
Moved package version from 4.1.x to 4.2.0 as it introduced new features, following semantic versioning.

### CODE REVIEW

**Comment by loechel** [comment]
@plone/framework-team @jensens this pull superseeds #23 (Stashed and merged commits) and implements PLIP: plone/Products.CMFPlone#1673

**Comment by pigeonflight** [comment]
What's involved/needed for a review?

**Comment by loechel** [comment]
@pigeonflight as this is a PLIP with @jensens as a champion assigned it just need some of his time and the next framework-team meeting to merge.

**Comment by jensens** [comment]
I did a quick review of the changes code wise and all looks well structured, code style is good. The implementation improves the code, its readability and functionality.

**Comment by jensens** [comment]
Since all is fine here I am going to merge.

**Pull request merged**
